### ISSUE TITLE
Cab emulation

### ISSUE THREAD

**Issue by mishushakov** [GuitarML/NeuralPi#1]
hi,
consider using JUCE Convolution class for adding impulse response for cabinet emulation
https://docs.juce.com/master/classdsp_1_1Convolution.html

**Comment by GuitarML** [comment]
That's a good idea, there's actually a lot of DSP functional built into JUCE that I'd like to learn too.

**Comment by GuitarML** [comment]
@mishushakov I have an ir-loader branch that will currently load and run IR's on the Mac/Windows plugin (no OSC messages yet), with a similar import button/dropdown menu as the ML models.  With the few IR's I tried out, it really adds depth and realism to the sound, especially for the pedal captures, which don't normally sound great by themselves. 

Looks like there are a handful of IR loading plugins in the MOD community, so this feature probably isn't as important for that, but it is nice to have a single plugin for both amp/pedal and cabinet simulation.

**Comment by GuitarML** [comment]
IR loading implemented in main branch with https://github.com/GuitarML/NeuralPi/pull/10
