### ISSUE TITLE
Run individual NeuralPi plugins on each input/output channel

### ISSUE THREAD

**Issue by digi-chris** [GuitarML/NeuralPi#19]
I have a use-case where I'm currently taking my guitar signal, splitting it to run through two different effects boards and then out to two separate amplifiers.

What I'd like to be able to do is use NeuralPi in place of my amps when playing at home, recording, or even potentially in a live scenario to a PA.

Since the NeuralPi + HifiBerry DAC/ADC has two input channels and two output channels, would it be possible to run two versions of NeuralPi in mono, and then set each NeuralPi to a different amplifier model?

I've been trying to get to grips with the Sushi configuration files just to see if I could at least run NeuralPi in mono on one channel only as a first step, but I'm not getting very far. Here's my config file at the moment:

```
{
    "host_config" : {
        "samplerate" : 44100
    },
    "tracks" : [
        {
            "name" : "channel1",
            "mode" : "mono",
            "inputs" : [
                {
                    "engine_bus" : 0,
                    "track_bus" : 0,
                    "engine_channel" : 0,
                    "track_channel" : 0
                }
            ],
            "outputs" : [
                {
                    "engine_bus" : 0,
                    "track_bus" : 0,
                    "engine_channel" : 0,
                    "track_channel" : 0
                }
            ],
            "plugins" : [
                {
                    "uid"  : "NeuralPi",
                    "path" : "/home/mind/plugins/NeuralPi.vst3",
                    "name" : "NeuralPi",
                    "type" : "vst3x"
                }
            ]
        },
        {
            "name" : "channel2",
            "mode" : "mono",
            "inputs" : [
                {
                    "engine_bus" : 0,
                    "track_bus" : 0,
                    "engine_channel" : 1,
                    "track_channel" : 1
                }
            ],
            "outputs" : [
                {
                    "engine_bus" : 0,
                    "track_bus" : 0,
                    "engine_channel" : 1,
                    "track_channel" : 1
                }
            ],
            "plugins" : [
                {
                    "uid"  : "NeuralPi",
                    "path" : "/home/mind/plugins/NeuralPi.vst3",
                    "name" : "NeuralPi",
                    "type" : "vst3x"
                }
            ]
        }
    ],
    "midi" : {
    }
}
```

This results in Sushi responding with:

`Failed to load tracks from Json config file`

I don't see anything in the documentation for Sushi that describes how to run one plugin on a specific channel.

So I guess my first question is,

- How do I run NeuralPi twice, one input and output from/to channel 0, and then again for channel 1?

.. and then secondly,

- I assume if I can get this far, my next problem is, how can I control both NeuralPi plugins? Assuming they'll both be listening on the same port, is something going to go wrong?

**Comment by digi-chris** [comment]
So, I think my JSON was incorrect earlier, but having corrected it, I'm starting to wonder if I have something wrong with Sushi?

As far as I can see, this should pass each channel through as mono signals, but it gives the same error as above:

```
{
    "host_config" : {
        "samplerate" : 48000
    },
    "tracks" : [
        {
            "name" : "main",
            "mode" : "mono",
            "inputs" : [
                {
                    "engine_channel" : 0,
                    "track_channel" : 0
                }
            ],
            "outputs" : [
                {
                    "engine_channel" : 0,
                    "track_channel" : 0
                }
            ],
            "plugins" : [
                {
                    "uid" : "sushi.testing.passthrough",
                    "name" : "passthrough",
                    "type" : "internal"
                }
            ]
        },
        {
            "name" : "main2",
            "mode" : "mono",
            "inputs" : [
                {
                    "engine_channel" : 1,
                    "track_channel" : 1
                }
            ],
            "outputs" : [
                {
                    "engine_channel" : 1,
                    "track_channel" : 1
                }
            ],
            "plugins" : [
                {
                    "uid" : "sushi.testing.passthrough",
                    "name" : "passthrough",
                    "type" : "internal"
                }
            ]
        }
    ],
    "midi" : {
        "cc_mappings": [
        ]
    }
}
```

If I remove the second track, then it works.

It also looks like NeuralPi is expecting a stereo out?

Is there anything major I'm doing wrong here, or is it just not really possible at the moment?

**Comment by digi-chris** [comment]
I'm going to close this as I think it's more a Sushi issue at the moment than NeuralPi.. but might revisit it if I can get Sushi working the way I want.

**Comment by GuitarML** [comment]
@digi-chris I think what you're trying to do may be possible, but not with the current NeuralPi code. Right now it's written to process on the first channel's buffer and then copy to the second buffer, so if it was rewritten to only output on one buffer, and then have the appropriate settings in the config file it may work. I haven't tried running two instances of NeuralPi on the Pi 4, so it would need to be tested to see how well it keeps up with real-time. It seems like it could, assuming the 16-18% cpu usage is doubled to 36%. To control them you would need to have unique listening ports for each plugin instance, and enter the correct ports your two controller plugins. 

That's an interesting use case, and I know other guitarists who do that. Probably the easiest thing to do with the current version of NeuralPi would be to use the Win/Mac plugin and run two instances in a DAW, and use that to control your channel output, either out to a PA or recording on separate tracks.

**Comment by digi-chris** [comment]
@GuitarML thanks for the reply - that's some useful information and might help me if I fork your code to give it a try. I just need to work out why Sushi isn't playing ball.

I'm trying to (hopefully) avoid using my Mac or PC's DAW for this. My aim really is to have something I can store in a portable box and plug in wherever I go. Using two VSTs on my PC would definitely work, but I'm keen to see if I could use NeuralPi on the Pi 4 and eventually house it in a 1U rackmount case. End result is you have a 2-in/2-out box that can have individual modelling on each channel, and potentially also record my dry signal at the same time for reprocessing/review later (that would be **really** hand after a band rehearsal!).
