### ISSUE TITLE
Syncing models between Raspberry Pi and external device

### ISSUE THREAD

**Issue by GuitarML** [GuitarML/NeuralPi#3]
Implement a method, preferably in c++ using no additional dependencies, to sync json model files between the Raspberry Pi and another device running the NeuralPi GUI. (see "osc-user-controls" feature branch). Currently, additional models must be uploaded to the Pi and imported on the other device separately. Implement a feature where the user can upload a model to the remote device using the NeuralPi GUI "Import Tone" button, and also send the model to the Rpi for NeuralPi to receive.  It would be beneficial to check and send new models from the Pi to the other device, so that new devices can access the models stored on the Pi. This transfer would be done over a local WiFi network, after specifying the Pi's IP and port number on the GUI.

Acceptance Criteria:
- Implement a model sync feature on the "osc-user-controls" feature branch
- Ability to transfer additional models from a device running NeuralPi GUI to the Pi, and reverse over a local WiFi network
- Model selection in the drop-down menu must be properly synced with the models on the Pi, either by a known ordering (alphabetical) or model ID.
- Using the c++ Standard Library (TCP/IP file transfer) would be nice, but an external script called from the plugin works too

**Comment by mishushakov** [comment]
IMHO, sending files from one computer to another over network is a problem that has already been solved

**Comment by GuitarML** [comment]
Lol yeah, it's a little more complicated in native c++ than I expected though, so I might end up just using an external script to scp files to and from the Pi.  For Windows, it looks like you'd just have to download OpenSSH.

This is what I found on TCP file transfer in c/c++:
https://stackoverflow.com/questions/25634483/send-binary-file-over-tcp-ip-connection

And I think the headers and some commands are slightly different in Windows vs. Linux

**Comment by mishushakov** [comment]
you can place models on a remote drive and mount the drive to the plugin directory
or use something like [syncthing](https://syncthing.net) to sync from device to device

**Comment by GuitarML** [comment]
True, I'd like to do everything through the plugin though and not make the user do extra steps like mount a drive, ideally just import models with the plugin GUI and update both the pi and the other computer in the background. Unless I'm misunderstanding that syncthing app.

**Comment by mishushakov** [comment]
file sharing has been [solved since 55 years](https://en.wikipedia.org/wiki/ARPANET)
so, good luck reinventing the wheel 🤣

ps. i appreciate the User-Experience thinking though

**Comment by GuitarML** [comment]
Reinventing the wheel would be writing a new internet protocol, I just want to use the same wheel on a different car! I think this will accomplish what I'm looking for:

```
# After importing new models from the GUI, copy all models from local computer to Rpi
scp <path-to-model-directory>/*  root@<ip-address-of-rpi>:<path-to-model-directory>
# Copy all models from Rpi to local computer (for connecting with a new computer)
scp root@<ip-address-of-rpi>:<path-to-model-directory>  <path-to-model-directory>/*  
```

This could be called as a system command from the plugin, or dynamically written to a script file and then run from the plugin. The only variable is the IP address of the Rpi, which I currently have as a writable label field in the osc-user-controls branch. This should work by default on Linux/Mac, and just requires OpenSSH for Windows, which I just found out has been included since 2018.  Also need to ensure that all models have unique names, otherwise they will be overwritten with each scp. I'm open to other suggestions, but this seems to be the simplest solution.

**Comment by mishushakov** [comment]
how would you handle user-input and errors though?
you'll just end up rewriting a ssh/sftp client imo

if you're really into it, maybe take a look at [libcurl](https://curl.se/libcurl/)

**Comment by GuitarML** [comment]
User input can be handled through the GUI, I used an elk plugin example to get ip address/port as user editable fields. Error handling is a good point though, going to have to think about that one. I'll look into libcurl, thanks!

**Comment by GuitarML** [comment]
Updated the osc-user-controls branch with "scripts" directory and model update scripts for Linux/Mac and Windows. The user will configure this file one time with the Rpi IP address and the applicable model paths, then run the script to sync models between the Raspberry Pi and the computer running the plugin GUI. Optionally, the user can use another preferred method of transferring model files to and from the Pi.

Scripts have been tested and work as intended.

Thanks @mishushakov for convincing me from going too far down the rabbit hole!

**Comment by mishushakov** [comment]
it's not like you wouldn't be able to share the models if that's not supported by plugin
models are just files
and there are already many known ways to send files...
