### ISSUE TITLE
Looking for high quality time-based effects to add

### ISSUE THREAD

**Issue by GuitarML** [GuitarML/NeuralPi#4]
I'm opening this issue as a place to recommend open source time based effects to add to NeuralPi. This includes effects like Reverb, Delay, Chorus, Flange. Ideally these would be high quality effects written in c++ without too many user controls, I'd like to keep it simple. As long as permissions allow, it could be modified to only include the most relevant controls.

The models sound good by themselves, but these effects would add a whole new dimension to NeuralPi's capability. I also know that JUCE has some DSP capability built in, including IR, but have not tested these features yet.

**Comment by dromer** [comment]
Surge is making quite a nice collection of effects, many of them time-based, can eye the source here: https://github.com/surge-synthesizer/surge/tree/main/src/common/dsp/effects

**Comment by romulka** [comment]
May be interesting:

https://github.com/BlokasLabs/modep
https://github.com/moddevices/mod-lv2-data

**Comment by dromer** [comment]
@romulka how are these repositories relevant in any way?

**Comment by GuitarML** [comment]
@romulka Are the plugins in the modep project open source? Either way thanks for the links, I'll be trying that out when I get a chance.

**Comment by dromer** [comment]
modep is a derivative of mod-host and everything in the repository is opensource, but realize that you are not pointing to upstream at all.

please take a step back and check what the upstream versions of these plugins are :)

**Comment by mishushakov** [comment]
related to #2

porting NeuralPi and/or Chameleon to LV2, would enable us to join the [MODEP](https://blokas.io/modep) pedalboard, which comes with lots of effects
it could especially be interesting hardware-wise, with the [pi stomp pedalboard](https://www.treefallsound.com/wiki/doku.php?id=pi-stomp_core), which runs MODEP

in personal view, i think we should stay a "neural pedal" and let the DAWs/MODEP manage all the other effects

😃

**Comment by GuitarML** [comment]
@mishushakov I like that idea a lot, and it shouldn't be to hard to build lv2 with the current cmake implementation. Ill start going down that route. Thanks!

**Comment by mishushakov** [comment]
great, thanks for letting everyone know!
moreover, i believe openness and flexibility is what allowed the project to become what it is

i only touched the surface of what mod is capable of, but speaking for myself, i'd rather prefer my Raspberry Pi to be a full pedalboard instead of a single effect 😃

**Comment by dromer** [comment]
Yup, I'm also playing a lot with MOD and the modular synth environment makes a lot of sense for me (it's how I use jack/pipewire and "pro audio" on linux). I also play a lot with physical hardware, so the integration feels very natural.


Having a couple basic/suitable effects internally is no shame though!
But I wouldn't go overkill and turn NeuralPI into more than what it needs to be.

**Comment by jfsantos** [comment]
Really interested in seeing this work ported to LV2! Do you have a public WIP repo to share at this point?

**Comment by GuitarML** [comment]
@jfsantos yes, the current main branch supports lv2 building with cmake, also reference this closed issue for build instructions:

https://github.com/GuitarML/NeuralPi/issues/2

**Comment by GuitarML** [comment]
Added IR, reverb, and delay using the juce::dsp module in release 1.2, closing this issue as the original intent has been resolved. We can continue LV2/MODEP conversation in a new discussion thread. Thanks!
